force-app/main/default/objects/Meeting__c/Meeting__c.object-meta.xml
<CustomObject>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participator__c/Participator__c.object-meta.xml
<CustomObject>
    <label>Participator</label>
    <nameField>
        <displayFormat>Participator-{00000}</displayFormat>
        <label>Participator Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participators</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participator__c/fields/Meeting__c.field-meta.xml
<CustomField>
    <fullName>Meeting__c</fullName>
    <label>Meeting</label>
    <referenceTo>Meeting__c</referenceTo>
    <relationshipLabel>Participators</relationshipLabel>
    <relationshipName>Participators</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participator__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Participators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ParticipatorTriggerHandler.cls
/**
 * Created by AntonAntoniuk on 15.10.2019.
 */

public with sharing class ParticipatorTriggerHandler {

    public ParticipatorTriggerHandler() {
    }

    public void checkUnique(List<Participator__c> newParticipators) {
        Set<Id> meetingIds = new Set<Id>();
        Set<Id> userIds = new Set<Id>();

        for (Participator__c participator : newParticipators) {
            meetingIds.add(participator.Meeting__c);
            userIds.add(participator.User__c);
        }

        List<Participator__c> existParticipators = [
                SELECT Id
                FROM Participator__c
                WHERE Meeting__c IN :meetingIds
                AND User__c IN :userIds
        ];
        if (!existParticipators.isEmpty()) {
            throw new ParticipatorTriggerHandlerException('This record exists!');
        }
    }

    public void blockUpdate() {
        throw new ParticipatorTriggerHandlerException('You could not update this record!');
    }

    private class ParticipatorTriggerHandlerException extends Exception {
    }
}