force-app/main/default/objects/Meeting__c/Meeting__c.object-meta.xml
<CustomObject>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting__c/fields/Ends_at__c.field-meta.xml
<CustomField>
    <fullName>Ends_at__c</fullName>
    <label>Ends at</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Meetings</relationshipLabel>
    <relationshipName>Meetings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Starts_at__c.field-meta.xml
<CustomField>
    <fullName>Starts_at__c</fullName>
    <label>Starts at</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/When__c.field-meta.xml
<CustomField>
    <fullName>When__c</fullName>
    <label>When</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Meeting_Participators_Log__c/Meeting_Participators_Log__c.object-meta.xml
<CustomObject>
    <label>Meeting Participators Log</label>
    <nameField>
        <displayFormat>MPLog-{00000}</displayFormat>
        <label>Meeting Participators Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Participators Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting_Participators_Log__c/fields/Meeting__c.field-meta.xml
<CustomField>
    <fullName>Meeting__c</fullName>
    <label>Meeting</label>
    <referenceTo>Meeting__c</referenceTo>
    <relationshipName>Notification_Meeting_Emails_Log</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Meeting_Participators_Log__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Notification_Meeting_Emails_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <displayFormat>Room - {0000}</displayFormat>
        <label>Room Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Room_Closes_at__c.field-meta.xml
<CustomField>
    <fullName>Room_Closes_at__c</fullName>
    <label>Room Closes at</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Room_Opens_at__c.field-meta.xml
<CustomField>
    <fullName>Room_Opens_at__c</fullName>
    <label>Room Opens at</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/classes/SendNotificationAboutMeetingChangesTest.cls
/**
 * Created by AntonAntoniuk on 16.10.2019.
 */

@IsTest
private class SendNotificationAboutMeetingChangesTest {
    @TestSetup
    static void createTestData() {
        UnitOfWork unitOfWork = new UnitOfWork(new Set<SObjectType>{
                User.SObjectType,
                Room__c.SObjectType,
                Meeting__c.SObjectType
        });

        List<User> users = new List<User>();
        List<Meeting__c> meetings = new List<Meeting__c>();
        Profile profile = [
                SELECT Id
                FROM Profile
                WHERE Name = 'Standard User'
                LIMIT 1
        ];

        Time roomOpenTime = Time.newInstance(8, 0, 0, 0);
        Time roomCloseTime = Time.newInstance(18, 0, 0, 0);

        Room__c room = new Room__c(Room_Opens_at__c = roomOpenTime, Room_Closes_at__c = roomCloseTime);
        unitOfWork.addToInsert(room);

        for (Integer i = 0; i < 5; i++) {
            Meeting__c meeting = new Meeting__c(
                    When__c = Date.today().addMonths(1),
                    Starts_at__c = Time.newInstance(8 + i * 2, 0, 0, 0),
                    Ends_at__c = Time.newInstance(8 + i * 2, 30, 0, 0));
            meetings.add(meeting);
            unitOfWork.addToInsert(meeting, Meeting__c.Room__c, room);

            for (Integer j = 0; j < 2; j++) {
                User testUser = new User(FirstName = 'Carl', LastName = 'Robinson', Alias = 'Robi', Email = 'antonantonuk1999@gmail.com',
                        Username = 'testUserProject1@gmail.com' + Datetime.now().getTime() + i + j, CommunityNickname = 'testUser' + i + j,
                        EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', ProfileId = profile.Id,
                        TimeZoneSidKey = 'America/Los_Angeles'
                );
                users.add(testUser);
                unitOfWork.addToInsert(testUser);
            }
        }
        unitOfWork.commitWork();

        unitOfWork = new UnitOfWork(new Set<SObjectType>{
                Meeting_Participators_Log__c.SObjectType
        });
        for (Integer i = 0; i < users.size(); i++) {
            Meeting_Participators_Log__c participator = new Meeting_Participators_Log__c(
                    Meeting__c = meetings[Math.mod(i, 5)].Id,
                    User__c = users[i].Id,
                    IsDeleted__c = false
            );
            unitOfWork.addToInsert(participator);
        }
        unitOfWork.commitWork();
    }

    @IsTest
    private static void testBehaviourToSend() {
        List<Meeting__c> meetings = [SELECT Id FROM Meeting__c];
        Set<Id> meetingIds = new Set<Id>();
        for (Meeting__c meeting : meetings) {
            meetingIds.add(meeting.Id);
        }

        Test.startTest();

        SendNotificationAboutMeetingChanges.sendEmails(meetingIds);
        Integer invocations = Limits.getEmailInvocations();

        Test.stopTest();

        System.assertEquals(10, invocations, 'Emails have been sent!');//todo
    }
}