force-app/main/default/objects/Meeting__c/Meeting__c.object-meta.xml
<CustomObject>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting_Participators_Log__c/Meeting_Participators_Log__c.object-meta.xml
<CustomObject>
    <label>Meeting Participators Log</label>
    <nameField>
        <displayFormat>MPLog-{00000}</displayFormat>
        <label>Meeting Participators Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Participators Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting_Participators_Log__c/fields/Meeting__c.field-meta.xml
<CustomField>
    <fullName>Meeting__c</fullName>
    <label>Meeting</label>
    <referenceTo>Meeting__c</referenceTo>
    <relationshipName>Notification_Meeting_Emails_Log</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Meeting_Participators_Log__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Notification_Meeting_Emails_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participator__c/Participator__c.object-meta.xml
<CustomObject>
    <label>Participator</label>
    <nameField>
        <displayFormat>Participator-{00000}</displayFormat>
        <label>Participator Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participators</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participator__c/fields/Meeting__c.field-meta.xml
<CustomField>
    <fullName>Meeting__c</fullName>
    <label>Meeting</label>
    <referenceTo>Meeting__c</referenceTo>
    <relationshipLabel>Participators</relationshipLabel>
    <relationshipName>Participators</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participator__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Participators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MeetingParticipatorsComponentController.cls
/**
 * Created by AntonAntoniuk on 15.10.2019.
 */

public with sharing class MeetingParticipatorsComponentController {

    @AuraEnabled
    public static List<User> getParticipators(String meetingId) {
        List<Participator__c> participators = [
                SELECT User__r.Id, User__r.LastName, User__r.FirstName
                FROM Participator__c
                WHERE Meeting__c = :meetingId
        ];

        List<User> resultUsers = new List<User>();
        for (Participator__c participator : participators) {
            resultUsers.add(new User(
                    Id = participator.User__r.Id,
                    LastName = participator.User__r.LastName,
                    FirstName = participator.User__r.FirstName));
        }
        return resultUsers;
    }

    @AuraEnabled
    public static void createLogParticipators(String meetingId) {
        List<Participator__c> participators = [
                SELECT User__c, Meeting__c
                FROM Participator__c
                WHERE Meeting__c = :meetingId
        ];

        List<Meeting_Participators_Log__c> participatorsLogs = new List<Meeting_Participators_Log__c>();
        for (Participator__c participator : participators) {
            participatorsLogs.add(new Meeting_Participators_Log__c(
                    Meeting__c = participator.Meeting__c,
                    User__c = participator.User__c,
                    IsDeleted__c = false
            ));
        }
        System.debug(participatorsLogs);
        insert participatorsLogs;
        System.debug([
                SELECT User__c, Meeting__c, IsDeleted__c
                FROM Meeting_Participators_Log__c
                WHERE Meeting__c = :meetingId
        ]);
    }

    @AuraEnabled
    public static void deleteAllParticipators(String meetingId) {
        delete [
                SELECT User__c
                FROM Participator__c
                WHERE Meeting__c = :meetingId
        ];
    }

    @AuraEnabled
    public static void deleteParticipator(String userId, String meetingId) {
        delete [
                SELECT Id
                FROM Participator__c
                WHERE Meeting__c = :meetingId AND User__c = :userId
        ];
    }
}