force-app/main/default/objects/Meeting__c/Meeting__c.object-meta.xml
<CustomObject>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting__c/fields/Ends_at__c.field-meta.xml
<CustomField>
    <fullName>Ends_at__c</fullName>
    <label>Ends at</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Meetings</relationshipLabel>
    <relationshipName>Meetings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Starts_at__c.field-meta.xml
<CustomField>
    <fullName>Starts_at__c</fullName>
    <label>Starts at</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/When__c.field-meta.xml
<CustomField>
    <fullName>When__c</fullName>
    <label>When</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <displayFormat>Room - {0000}</displayFormat>
        <label>Room Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MeetingTriggerHandler.cls
/**
 * Created by AntonAntoniuk on 09.10.2019.
 */

public with sharing class MeetingTriggerHandler {
    public MeetingTriggerHandler() {
    }

    public void checkIsDateAndTimeAreFreeOnInsert(List<Meeting__c> newMeetings) {
        List<Meeting__c> existMeetings = getExistMeetings(newMeetings);

        Map<Date, List<Meeting__c>> existMeetingsByDates = new Map<Date, List<Meeting__c>>();
        for (Meeting__c existMeeting : existMeetings) {
            if (!existMeetingsByDates.containsKey(existMeeting.When__c)) {
                existMeetingsByDates.put(existMeeting.When__c, new List<Meeting__c>());
            }
            existMeetingsByDates.get(existMeeting.When__c).add(existMeeting);
        }

        for (Meeting__c newMeeting : newMeetings) {
            if (existMeetingsByDates.containsKey(newMeeting.When__c)) {
                for (Meeting__c existMeeting : existMeetingsByDates.get(newMeeting.When__c)) {
                    checkCollision(newMeeting, existMeeting);
                }
            }
        }
    }

    public void checkIsDateAndTimeAreFreeOnUpdate(List<Meeting__c> newMeetings) {
        List<Meeting__c> existMeetings = getExistMeetings(newMeetings);

        Map<Id, Meeting__c> newMeetingsByIds = new Map<Id, Meeting__c>(newMeetings);
        Map<Date, List<Meeting__c>> existMeetingsByDates = new Map<Date, List<Meeting__c>>();

        for (Meeting__c existMeeting : existMeetings) {
            if (newMeetingsByIds.containsKey(existMeeting.Id)) continue;
            if (!existMeetingsByDates.containsKey(existMeeting.When__c)) {
                existMeetingsByDates.put(existMeeting.When__c, new List<Meeting__c>());
            }
            existMeetingsByDates.get(existMeeting.When__c).add(existMeeting);
        }

        for (Meeting__c newMeeting : newMeetings) {
            if (existMeetingsByDates.containsKey(newMeeting.When__c)) {
                for (Meeting__c existMeeting : existMeetingsByDates.get(newMeeting.When__c)) {
                    if (newMeeting.Room__c == existMeeting.Room__c) {
                        checkCollision(newMeeting, existMeeting);
                    }
                }
            }
        }
    }

    private List<Meeting__c> getExistMeetings(List<Meeting__c> newMeetings) {
        Set<Date> meetingsDays = new Set<Date>();
        Set<Id> rooms = new Set<Id>();

        for (Meeting__c newMeeting : newMeetings) {
            meetingsDays.add(newMeeting.When__c);
            rooms.add(newMeeting.Room__c);
        }

        List<Meeting__c> existMeetings = [
                SELECT Starts_at__c, Ends_at__c, When__c, Room__c
                FROM Meeting__c
                WHERE When__c = :meetingsDays
                AND Room__c = :rooms
        ];
        return existMeetings;
    }

    private void checkCollision(Meeting__c newMeeting, Meeting__c existMeeting) {
        if (newMeeting.Starts_at__c < existMeeting.Starts_at__c
                && newMeeting.Ends_at__c > existMeeting.Starts_at__c) {
            throw new MeetingException('You should choose another time cause it`s busy!');
        } else if (newMeeting.Starts_at__c < existMeeting.Ends_at__c
                && newMeeting.Ends_at__c > existMeeting.Ends_at__c) {
            throw new MeetingException('You should choose another time cause it`s busy!');
        } else if (newMeeting.Starts_at__c >= existMeeting.Starts_at__c
                && newMeeting.Ends_at__c <= existMeeting.Ends_at__c) {
            throw new MeetingException('You should choose another time cause it`s busy!');
        }
    }

    @TestVisible
    class MeetingException extends Exception {
    }
}